#!/bin/sh

. /lib/functions.sh

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0
	/etc/pressed
	return 5
;;
timeout)
	[ -z "$OVERLAY" ] && return 0
	/etc/timeout
;;
released)
	if [ "$SEEN" -ge 5 -a -n "$OVERLAY" ]
	then
		echo "FACTORY RESET" > /dev/console
		cp /etc/backup/passwall /etc/config/passwall
		cp /etc/backup/network /etc/config/network
		cp /etc/backup/system /etc/config/system
		cp /etc/backup/wireless /etc/config/wireless
		cp /etc/backup/dhcp /etc/config/dhcp
		rm /etc/rc.second.lock
	fi

	sync
	reboot
;;
esac

return 0
